global:
  scrape_interval: 5s  # 5초 간격으로 메트릭 수집
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']   # <서비스명:포트> 형식으로, Compose 네트워크 내 컨테이너 호스트명 사용